### ISSUE TITLE
Support bluetooth through Pico-BLE ?

### ISSUE THREAD

**Issue by zonetw** [beekeeb/piantor#6]
I saw a module that can extend Pico to use Pico.
https://detail.tmall.com/item_o.htm?spm=a230r.1.14.3.5b876a678HzI6f&abbucket=15&ns=1&releaseId=368216&bucketId=518000&id=696942327882&fbclid=IwAR2oCqNSngqnUsdNqu0lODWyCuugVSu8yv243aTVnz5hjKwXuEBntk5nL54

Not sure if this would work with the offical firmware?

**Comment by l4u** [comment]
https://www.waveshare.com/wiki/Pico-BLE
I'm not aware of firmwares supporting the Pico-BLE. KMK with modifications might work. It seems to be designed as a wired bluetooth host instead of a battery-powered device.

There're other issues such as battery charging and power usage, comparing to the existing nrf52 solutions.
